// <auto-generated />
namespace QuestionsSolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class point_added_teacher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(point_added_teacher));
        
        string IMigrationMetadata.Id
        {
            get { return "202304140106086_point_added_teacher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
