// <auto-generated />
namespace QuestionsSolution.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class approval_deleted_question : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(approval_deleted_question));
        
        string IMigrationMetadata.Id
        {
            get { return "202304140100581_approval_deleted_question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
